# Generated by Django 4.2.3 on 2023-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False),
        ),
    ]
