# Generated by Django 4.2.3 on 2023-07-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0002_alternativa_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='tema',
            field=models.CharField(default='Tema', max_length=50),
        ),
    ]
