# Generated by Django 4.2.3 on 2023-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0003_simulado_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='pontuacao',
            field=models.IntegerField(default=1),
        ),
    ]
